name: attendance_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.9
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter  

flutter:  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/nav/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
