name: attendance_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  detect_fake_location: ^2.1.0
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  # flutter_local_notifications: ^19.0.0
  flutter_svg: ^2.0.9
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.10.1
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.10.1
  image: ^4.5.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  location: ^8.0.0
  logger: ^2.5.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/nav/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
